#
# This is the config file for this Jekyll blog.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# The variables herein can be accessed via {{ site.title }}, {{ site.email }},
# and so on.
#
title: "libGDX"
minimal_mistakes_skin: "default"
minimal_mistakes_skin_dark: "dark"

logo: "/assets/brand/logo.svg"
logo_dark: "/assets/brand/logo_dark.svg"
masthead_title: " " # disable the written title in the header
description: "From paddling townships to the chimes of the greatest cities, markets crowd with the exchange of wears. Across the hilltops away, a crew of toolsmiths follow the blueprints to create factory machinery - replicable ones at that. Finally, at the port side bays, in an undistinguished warehouse, a new line of ships will break the waves. A new era is beginning. Don't get left behind."
github_username: libgdx
enable_copy_code_button: true

repository: libgdx/libgdx.github.io
url: https://libgdx.com
baseurl: "" # prevent jekyll-github-metadata from setting an unwanted default value

# Search, Google
google_site_verification: "qc0iys9Aweas1z8EhICO-0Ohwh6Iq1GDV6K75e0ToO8"
search: false

# Open Graph
og_image: /assets/images/logo.png # default open graph (= social media) image

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.26.2 # 2024-06-15; when updating this, the theme overrides in _includes, _layouts and _sass should be adapted accordingly!

future: false # allow scheduling posts

# Outputting
permalink: /:categories/:year/:month/:title
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-github-metadata
#  - jekyll-last-modified-at

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/libgdx/libgdx"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "/community/discord/"
    - label: "Wiki"
      icon: "fas fa-fw fa-link"
      url: "/wiki/"
    - label: "Patreon"
      icon: "fab fa-fw fa-patreon"
      url: "https://www.patreon.com/libgdx"

# Content
include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
      show_date: true
      show_author: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # wiki
  - scope:
      path: "wiki"
      type: pages
    values:
      layout: wiki
